$ErrorActionPreference='Stop'; Set-StrictMode -Version Latest
function H($p){(Get-FileHash -Algorithm SHA256 -LiteralPath $p).Hash.ToLowerInvariant()}
function B($p){$x=(git hash-object --no-filters -- $p).Trim();if($LASTEXITCODE){throw "hash-object $p"};$x}
function Gz($s,$d){$i=[IO.File]::OpenRead($s);try{$g=[IO.Compression.GzipStream]::new($i,[IO.Compression.CompressionMode]::Decompress);try{$o=[IO.File]::Create($d);try{$g.CopyTo($o)}finally{$o.Dispose()}}finally{$g.Dispose()}}finally{$i.Dispose()}}
function Cat($a,$d){$o=[IO.File]::Create($d);try{foreach($p in $a){$b=[IO.File]::ReadAllBytes($p);$o.Write($b,0,$b.Length)}}finally{$o.Dispose()}}
function R($n,[scriptblock]$c){$global:LASTEXITCODE=0;$o=@(& $c 2>&1);$q=$LASTEXITCODE;$o|Set-Content -Encoding utf8 (Join-Path $env:EVIDENCE $n);$o|Out-Host;if($q){throw "$n exit $q"};,$o}
function CleanPy($r){Get-ChildItem $r -Directory -Filter __pycache__ -Recurse -ErrorAction Ignore|Remove-Item -Recurse -Force;Get-ChildItem $r -File -Filter *.pyc -Recurse -ErrorAction Ignore|Remove-Item -Force}
try{
  $stage='baseline';@('RUNNER_NAME='+$env:RUNNER_NAME,'RUNNER_OS='+$env:RUNNER_OS,'RUNNER_ARCH='+$env:RUNNER_ARCH,'COMPUTERNAME='+$env:COMPUTERNAME,'POWERSHELL='+$PSVersionTable.PSVersion.ToString())|Set-Content (Join-Path $env:EVIDENCE runner-identity.txt);if($env:RUNNER_OS -ne 'Windows' -or $env:RUNNER_ARCH -ne 'X64'){throw 'runner identity'};git config core.autocrlf false;git config core.eol lf;git reset --hard $env:BASELINE_SHA|Out-Host;if($LASTEXITCODE){throw 'baseline reset'}
  if((git rev-parse HEAD).Trim() -ne $env:BASELINE_SHA){throw 'baseline SHA'};if((git rev-parse 'HEAD^{tree}').Trim() -ne $env:BASELINE_TREE){throw 'baseline tree'};if(@(git status --short).Count -ne 0){throw 'baseline dirty'}
  $rr=@(git ls-remote --heads origin "refs/heads/$env:RESULT_BRANCH");if($LASTEXITCODE){throw 'result branch probe'};if($rr.Count -ne 0){throw 'result branch exists'};git switch -c $env:RESULT_BRANCH;if($LASTEXITCODE){throw 'result branch create'};git config user.name github-actions[bot];git config user.email 41898282+github-actions[bot]@users.noreply.github.com
  $stage='A';$sr='Tools/EngineSimVendor/_cold_start_sources';$ap=@('Tools/EngineSimVendor/generate_cold_start_profile_header.py','Tools/EngineSimVendor/record_cold_start_calibration_evidence.py','Tools/EngineSimVendor/run_cold_start_calibration.py','Tools/EngineSimVendor/verify_cold_start_profile.py','Tools/EngineSimVendor/tests/test_cold_start_profile_verifier.py','Tools/EngineSimVendor/_cold_start_sources/generate_cold_start_profile_header.py.gz','Tools/EngineSimVendor/_cold_start_sources/record_cold_start_calibration_evidence.py.gz','Tools/EngineSimVendor/_cold_start_sources/run_cold_start_calibration.py.gz','Tools/EngineSimVendor/_cold_start_sources/verify_cold_start_profile.py.gz','Tools/EngineSimVendor/_cold_start_sources/test_cold_start_profile_verifier.py.gz')
  $rows=@(@('generate_cold_start_profile_header.py.gz',$ap[0],'6efb3d29734c2d41c96d16e914ab460cd212769d611ba08cf2677377d933659d','4ec6534979528b440b532b72ec33e6ea27d7e3c0'),@('record_cold_start_calibration_evidence.py.gz',$ap[1],'f1ee52d8d2df40df5dad19aaf97bf796cf4ef32c1bd5b60700fec4ef48c99357','04ba4e3eedc5ec53af7af7c5ea0468e29eb3ba01'),@('run_cold_start_calibration.py.gz',$ap[2],'b70387026d05679f5760e1cc1927197c8a14ca91fdac3af1ffbf3aa9a081264b','5117fc9f7c7799a7f4a034cd8653bc8bc45d36f6'),@('verify_cold_start_profile.py.gz',$ap[3],'92b4ebdb922b409cf8c583fc7c7d7cb56a16dd70606c2080673ef6dc77e7d57d','b858f4b5a46a53d03036909b2099b0f6f55887ee'))
  foreach($r in $rows){$s=Join-Path $sr $r[0];Gz $s $r[1];Remove-Item $s;if((H $r[1]) -ne $r[2] -or (B $r[1]) -ne $r[3]){throw "A identity $($r[1])"}}
  $ts=Join-Path $sr 'test_cold_start_profile_verifier.py.gz';Gz $ts $ap[4];Remove-Item $ts
  $e="import hashlib;from pathlib import Path;p=Path(r'$($ap[4])');d=p.read_bytes();L=d.splitlines(True);h='3be9f2edeb76eea09b844911202619b497af7aab04018af06569cf4067cd5036';c=[];[(c.append(b''.join(L[:s]+L[e:]))) for s in range(len(L)) for e in range(s+1,min(len(L),s+41)+1) if b'_cold_start_sources' in b''.join(L[s:e]) and b''.join(L[s:e]).count(b'.py.gz')==2 and hashlib.sha256(b''.join(L[:s]+L[e:])).hexdigest()==h];assert len(c)==1,len(c);p.write_bytes(c[0])";python -B -c $e;if($LASTEXITCODE -or (H $ap[4]) -ne '3be9f2edeb76eea09b844911202619b497af7aab04018af06569cf4067cd5036' -or (B $ap[4]) -ne 'f8bb81c8a1bcfef2126bbff2cac717dd6db1e055'){throw 'A test identity'};Remove-Item $sr -Recurse
  $aa=@(git status --short|%{$_.Substring(3)}|sort);if(@(Compare-Object ($ap|sort) $aa).Count){throw 'A scope'};git add -A -- $ap;if($LASTEXITCODE){throw 'A add'};git commit -m 'WIP Phase 0: normalize cold-start Python sources';if($LASTEXITCODE){throw 'A commit'};$ca=(git rev-parse HEAD).Trim();$ta=(git rev-parse 'HEAD^{tree}').Trim();$as=@(git diff-tree --no-commit-id --name-status -r HEAD);if(@($as|?{$_ -match '^M\s'}).Count -ne 5 -or @($as|?{$_ -match '^D\s'}).Count -ne 5 -or $as.Count -ne 10){throw 'A 5M/5D'}
  $stage='G';$ps='Tools/EngineSimVendor/validate_cold_start_windows.ps1';$cpp='Plugins/NextcarEngineSim/Source/NextcarEngineSimCore/Private/Calibration/ColdStartCalibrationHarness.cpp';$v='scripts/validate_repository.py';$pp=@(0..4|%{"Tools/EngineSimVendor/validate_cold_start_windows.parts/part$($_.ToString('00')).ps1frag"});$cp=@(0..2|%{"Plugins/NextcarEngineSim/Source/NextcarEngineSimCore/Private/Calibration/ColdStartCalibrationHarness.part$($_.ToString('00')).inc"});$gp=@($ps,$cpp,$v)+$pp+$cp
  Cat $pp $ps;Cat $cp $cpp;if((Get-Item $ps).Length -ne 22230 -or (H $ps) -ne '10ee201b5136864012a3e975989d8ed9ded47dbf7813e1c9d0e11e82900d4f13' -or (B $ps) -ne '29973abfc14829d2f7cb00f273f288dfef8b146f'){throw 'PS identity'};if((Get-Item $cpp).Length -ne 19971 -or (H $cpp) -ne 'bb67a62743ef28e41fdfe977b7aad2ab5dbdd799c50447bd7bcaf426e1d2b83d' -or (B $cpp) -ne 'ac5003693875afbcc0513075d04a2490bbbc806a'){throw 'CPP identity'}
  $vs=Join-Path $env:GITHUB_WORKSPACE 'bootstrap\.github\nc003b-bootstrap\validate_repository.py';Copy-Item $vs $v -Force;if((Get-Item $v).Length -ne 11105 -or (H $v) -ne 'aae52e31fb11ffab7791a3b3c33dbef73faa0d753df977939011b28fb0b8341d' -or (B $v) -ne '65c309558f1e50a8258caaef61e38087f2382392'){throw 'validator identity'};Remove-Item 'Tools/EngineSimVendor/validate_cold_start_windows.parts' -Recurse;Remove-Item $cp
  $ga=@(git status --short|%{$_.Substring(3)}|sort);if(@(Compare-Object ($gp|sort) $ga).Count){throw 'G scope'};git add -A -- $gp;if($LASTEXITCODE){throw 'G add'};git commit -m 'WIP Phase 0: normalize boundary source files';if($LASTEXITCODE){throw 'G commit'};$cg=(git rev-parse HEAD).Trim();$tg=(git rev-parse 'HEAD^{tree}').Trim();$gs=@(git diff-tree --no-commit-id --name-status -r HEAD);if(@($gs|?{$_ -match '^M\s'}).Count -ne 3 -or @($gs|?{$_ -match '^D\s'}).Count -ne 8 -or $gs.Count -ne 11){throw 'G 3M/8D'}
  $stage='21-path scope';$ns=@(git diff --name-status $env:BASELINE_SHA HEAD);if(@($ns|?{$_ -match '^M\s'}).Count -ne 8 -or @($ns|?{$_ -match '^D\s'}).Count -ne 13 -or $ns.Count -ne 21){throw 'combined 8M/13D/21'};$all=@(($ap+$gp)|sort);$got=@($ns|%{($_ -split "\t",2)[1]}|sort);if(@(Compare-Object $all $got).Count){throw 'allowlist'};if(@(git ls-tree -r --name-only HEAD|?{$_ -eq '.github/workflows/nc003b-source-normalization-bootstrap.yml'}).Count -ne 0){throw 'bootstrap workflow leaked'};$ns|Set-Content (Join-Path $env:EVIDENCE changed-paths.txt);@("A=$ca/$ta","G=$cg/$tg")|Set-Content (Join-Path $env:EVIDENCE commit-identities.txt)
  $stage='validator/mutations';R repository-validation.txt {python -B scripts/validate_repository.py}|Out-Null;$m=@(@('dir','Tools/EngineSimVendor/_cold_start_sources',''),@('file','Tools/EngineSimVendor/probe.py.gz','x'),@('file','Tools/EngineSimVendor/probe.ps1frag','x'),@('dir','Tools/EngineSimVendor/validate_cold_start_windows.parts',''),@('file','Plugins/NextcarEngineSim/Source/NextcarEngineSimCore/Private/Calibration/Probe.part00.inc','x'),@('file','Tools/EngineSimVendor/probe.py',"import gzip`np=gzip.decompress(b'x')`nexec(compile(p,'x','exec'))"),@('file','Tools/EngineSimVendor/probe.ps1',"[ScriptBlock]::Create('x')"));foreach($x in $m){if($x[0] -eq 'dir'){New-Item -ItemType Directory $x[1]|Out-Null}else{[IO.File]::WriteAllText((Join-Path (Get-Location) $x[1]),$x[2],[Text.UTF8Encoding]::new($false))};python -B scripts/validate_repository.py 2>&1|Add-Content (Join-Path $env:EVIDENCE mutation.txt);$q=$LASTEXITCODE;Remove-Item $x[1] -Recurse -Force;if(-not $q){throw "accepted $($x[1])"};if(@(git status --short).Count -ne 0){throw 'dirty after probe'}};$o='Plugins/NextcarEngineSim/Source/NextcarEngineSimCore/Private/Calibration/Ordinary.inc';[IO.File]::WriteAllText((Join-Path (Get-Location) $o),'int x;',[Text.UTF8Encoding]::new($false));python -B scripts/validate_repository.py|Out-Null;$q=$LASTEXITCODE;Remove-Item $o;if($q -or @(git status --short).Count -ne 0){throw 'Ordinary.inc'};$t=$null;$pe=$null;[void][Management.Automation.Language.Parser]::ParseFile((Resolve-Path $ps),[ref]$t,[ref]$pe);if($pe.Count){throw 'PowerShell AST'};git diff --check $env:BASELINE_SHA HEAD;if($LASTEXITCODE){throw 'diff-check'}
  $stage='Python gates';$u=R cold-tests.txt {python -B -m unittest -v Tools/EngineSimVendor/tests/test_cold_start_profile_verifier.py};if(($u -join "`n") -notmatch 'Ran 15 tests'){throw '15 tests'};R orchestrator-self-test.txt {python -B Tools/EngineSimVendor/run_cold_start_calibration.py self-test}|Out-Null;R snapshot.txt {python -B Tools/EngineSimVendor/verify_fixture_source_snapshot.py}|Out-Null;$u=R snapshot-unit.txt {python -B -m unittest -v Tools/EngineSimVendor/tests/test_fixture_source_snapshot.py};if(($u -join "`n") -notmatch 'Ran 7 tests'){throw '7 tests'};$u=R fixture.txt {python -B -m unittest -v Tools/EngineSimVendor/tests/test_subaru_ej25_fixture_verifier.py};$p=R parity.txt {python -B Tools/EngineSimVendor/verify_subaru_ej25_fixture.py};if(($u -join "`n") -notmatch 'Ran 24 tests' -or ($p -join "`n") -notmatch '118/118'){throw 'fixture counts'};$u=R ir.txt {python -B -m unittest -v Tools/EngineSimVendor/tests/test_impulse_response_tools.py};if(($u -join "`n") -notmatch 'Ran 11 tests'){throw 'IR count'}
  $vo=@(python -B Tools/EngineSimVendor/verify_cold_start_profile.py --profile Tests/EngineSimCore/Fixtures/subaru_ej25_cold_start_profile.json --repo-root . 2>&1);$q=$LASTEXITCODE;$vo|Set-Content (Join-Path $env:EVIDENCE expected-drift.txt);$z=(($vo -join "`n") -replace 'generator SHA mismatch','');if(-not $q -or ($vo -join "`n") -notmatch 'generator SHA mismatch' -or $z -match '(?i)(mismatch|error|FAIL:)'){throw 'verifier drift'};CleanPy (Get-Location)
  $stage='Windows matrix';$sm=Get-ChildItem (Join-Path $env:RUNNER_TEMP accepted-closure) -Filter selected-summary.json -File -Recurse|select -First 1;if(-not $sm){throw 'accepted selected-summary'};$j=Get-Content $sm.FullName -Raw|ConvertFrom-Json;$sel=Join-Path $env:RUNNER_TEMP selected.json;[IO.File]::WriteAllText($sel,(ConvertTo-Json ([ordered]@{schema_version=$j.schema_version;candidate_source_sha=$j.candidate_source_sha;selected_candidate=$j.selected_candidate}) -Depth 12),[Text.UTF8Encoding]::new($false))
  $mr=Join-Path $env:RUNNER_TEMP matrix;$mw=Join-Path $mr work;$br=Join-Path $mr release;$bd=Join-Path $mr debug;$ba=Join-Path $mr asan;$out=Join-Path $mr trials;$rep=Join-Path $mr repro;$me=Join-Path $env:EVIDENCE matrix;Remove-Item $mr,$me -Recurse -Force -ErrorAction Ignore;New-Item -ItemType Directory $me|Out-Null;git worktree add --detach $mw $cg;if($LASTEXITCODE){throw 'worktree'}
  try{Push-Location $mw;$vw="${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe";$vp=(&$vw -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath).Trim();$dc=Join-Path $vp 'Common7\Tools\VsDevCmd.bat';cmd /s /c "`"$dc`" -arch=x64 -host_arch=x64 >nul && set"|%{if($_ -match '^([^=]+)=(.*)$'){[Environment]::SetEnvironmentVariable($matches[1],$matches[2],'Process')}};if($LASTEXITCODE){throw 'VsDevCmd'}
    function M($n,[scriptblock]$c){$global:LASTEXITCODE=0;$o=@(& $c 2>&1);$q=$LASTEXITCODE;$o|Set-Content (Join-Path $me $n);$o|Out-Host;if($q){throw "$n exit $q"}}
    function C($b,$x){$a=@('-S',(Join-Path $mw 'Tools/EngineSimVendor/Standalone'),'-B',$b,'-G','Visual Studio 17 2022','-A','x64','-T','v143')+$x;M "$(Split-Path $b -Leaf)-configure.log" {cmake @a}}
    C $br @();M release-build.log {cmake --build $br --config Release --verbose};M release-ctest.log {ctest --test-dir $br -C Release --output-on-failure};M release-runtime.log {& (Join-Path $br 'Release\nc003b_cold_start_profile_tests.exe')}
    C $bd @();if((Get-Content (Join-Path $bd CMakeCache.txt)|?{$_ -match '^CMAKE_CXX_FLAGS_DEBUG:'}) -notmatch '/RTC1'){throw '/RTC1'};M debug-build.log {cmake --build $bd --config Debug --verbose};M debug-ctest.log {ctest --test-dir $bd -C Debug --output-on-failure}
    C $ba @('-DCMAKE_CXX_FLAGS_RELWITHDEBINFO=/O1 /Zi /fsanitize=address','-DCMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO=/DEBUG /INCREMENTAL:NO');M asan-build.log {cmake --build $ba --config RelWithDebInfo --verbose};$ad=Get-ChildItem $env:VCToolsInstallDir -Filter clang_rt.asan_dynamic-x86_64.dll -File -Recurse -ErrorAction Ignore|select -Last 1;if(-not $ad){throw 'ASAN DLL'};$env:PATH="$($ad.DirectoryName);$env:PATH";$env:ASAN_OPTIONS='abort_on_error=true:alloc_dealloc_mismatch=true';M asan-ctest.log {ctest --test-dir $ba -C RelWithDebInfo --output-on-failure}
    M self-test.log {python -B Tools/EngineSimVendor/run_cold_start_calibration.py self-test};$exe=Join-Path $br 'Release\nc003b_cold_start_calibration.exe';M trials.log {python -B Tools/EngineSimVendor/run_cold_start_calibration.py selected --executable $exe --sweep Tests/EngineSimCore/Fixtures/subaru_ej25_cold_start_sweep.json --selected-candidate $sel --output $out --repo-root $mw --candidate-sha $cg --trials 10};$sj=Get-Content (Join-Path $out selected-summary.json)-Raw|ConvertFrom-Json;if($sj.selected_trial_count -ne 10 -or $sj.success_count -ne 10 -or $sj.failure_count -ne 0 -or $sj.timeout_trace.result -ne 'Timeout' -or $sj.stall_trace.result -ne 'StallAfterDisengagement'){throw 'trial semantics'};$h1=@(Get-ChildItem $out -File -Recurse|?{$_.Name -match '^(trial-\d+|negative-(timeout|stall))\.json$'}|sort FullName|%{H $_.FullName});M repro.log {python -B Tools/EngineSimVendor/run_cold_start_calibration.py selected --executable $exe --sweep Tests/EngineSimCore/Fixtures/subaru_ej25_cold_start_sweep.json --selected-candidate $sel --output $rep --repo-root $mw --candidate-sha $cg --trials 10};$h2=@(Get-ChildItem $rep -File -Recurse|?{$_.Name -match '^(trial-\d+|negative-(timeout|stall))\.json$'}|sort FullName|%{H $_.FullName});if(($h1 -join ',') -ne ($h2 -join ',')){throw 'repro'};$warn=@(Get-ChildItem $me -Filter *-build.log|%{Select-String $_.FullName 'warning C\d+:'}|%{$_.Line}|?{$_ -match 'NextcarEngineSimCore|Standalone[\\/](calibration|tests)|ColdStartCalibration'});if($warn.Count){throw "warnings $($warn.Count)"};if(@(git status --short).Count -ne 0){throw 'matrix status'};if(@(git diff).Count -ne 0){throw 'matrix diff'};if(@(Get-ChildItem $mw -Directory -Filter __pycache__ -Recurse -ErrorAction Ignore).Count -ne 0 -or @(Get-ChildItem $mw -File -Filter *.pyc -Recurse -ErrorAction Ignore).Count -ne 0){throw 'matrix pycache'};@('Release PASS','Debug /RTC1 PASS','ASan PASS','CTest/runtime PASS','self-test PASS','trials 10/10 PASS','timeout PASS','stall PASS','repro PASS','warnings 0','status/diff empty','pycache/pyc 0')|Set-Content (Join-Path $me summary.txt)
  }finally{Pop-Location;git worktree remove --force $mw|Out-Null;git worktree prune|Out-Null}
  $stage='pre-push';CleanPy (Get-Location);if(@(git status --short).Count -ne 0){throw 'final status'};if(@(git diff).Count -ne 0){throw 'final diff'};if(@(Get-ChildItem . -Directory -Filter __pycache__ -Recurse -ErrorAction Ignore).Count -ne 0 -or @(Get-ChildItem . -File -Filter *.pyc -Recurse -ErrorAction Ignore).Count -ne 0){throw 'final pycache'};if((git rev-list --count "$env:BASELINE_SHA..HEAD").Trim() -ne '2'){throw 'commit count'};"FINAL_HEAD=$cg"|Out-File $env:GITHUB_ENV -Append;"FINAL_TREE=$tg"|Out-File $env:GITHUB_ENV -Append;"VALIDATED — UPLOAD/PUSH PENDING`nhead=$cg`ntree=$tg"|Set-Content (Join-Path $env:EVIDENCE final-status.txt)
}catch{"STOP — $stage: $($_.Exception.Message)"|Set-Content (Join-Path $env:EVIDENCE final-status.txt);throw}
